### ISSUE TITLE
Add adzfree-watch.net

### ISSUE THREAD

**Issue by brunof0d2** [durablenapkin/scamblocklist#10]
Hello,
This domain use a webpage (https://adzfree-watch.net / addto.php?dt=bjpa4534Mel1&ea=4113378&dw=661795107737178429&dv=pa&rdk=rk1 for ex) to install false adguard extensions.
regards

**Comment by durablenapkin** [comment]
Thank you! Queued to be added in the next nightly update (in ~6 hours)
