### ISSUE TITLE
robux and other giftcards live youtube scam

### ISSUE THREAD

**Issue by cinatime** [durablenapkin/scamblocklist#15]
collectivebux.com
boostrobux.com
robuxmenu.vip
thuthuatxiaomi.com
petsimulator.live
robuxclaims.live
robuxreward.live
uplevelreward.com
claimsrobux.live
petsimulator.live
rewardsgiantca.com
earnpets.com

Live streams
https://www.youtube.com/watch?v=aP--6GjUQio
https://www.youtube.com/watch?v=KmdThH7qNmg
https://www.youtube.com/watch?v=wvf4mb6PF-I
https://www.youtube.com/watch?v=C1UsS8zGFKY
https://www.youtube.com/watch?v=bgv5Bnsiti0
https://www.youtube.com/watch?v=Ch6Xui-nZ9o
https://www.youtube.com/watch?v=hT06PRbvzgk
https://www.youtube.com/watch?v=DLgiCiA3xxQ
https://www.youtube.com/watch?v=sxfyFsrdrhw
https://www.youtube.com/watch?v=l8Qb3eTIa_c
https://www.youtube.com/watch?v=zapTFL9Bt1s
https://www.youtube.com/watch?v=yCwD-jgTC1g

**Comment by durablenapkin** [comment]
Thanks, queued
