### ISSUE TITLE
Badware

### ISSUE THREAD

**Issue by flav0ring** [durablenapkin/scamblocklist#27]
`cracksway.com`
https://www.virustotal.com/gui/url/f906b6aea8ada1b1389e2395e44cf9e67900c8c9f2ca51b2aae381007b6bd494?nocache=1

`crackedpc.org`
https://www.virustotal.com/gui/url/1d7c032647641ca052782d4e040788f7eac76d8cfbeef2b1e55720784976d9f8?nocache=1

**Comment by durablenapkin** [comment]
Thank you :) Queued
