### ISSUE TITLE
Fake "free" games on steam

### ISSUE THREAD

**Issue by felcerreia** [durablenapkin/scamblocklist#3]
steamgateways.com (https://www.trustpilot.com/review/steamgateways.com)
steamunlock.gifts and steamunlock.com (https://www.trustpilot.com/review/steamunlock.com)

**Comment by durablenapkin** [comment]
Thank you! Added: https://github.com/durablenapkin/scamblocklist/commit/f53482aa3f91b4ef2dd05af62199eaf157fa454e
