### ISSUE TITLE
danegreatjp.blob.core.windows.net

### ISSUE THREAD

**Issue by flav0ring** [durablenapkin/scamblocklist#30]
`https://danegreatjp.blob.core.windows.net/$web/JPbex/tujpP/xdsxwrxxokisawachjp/index.html`
https://www.virustotal.com/gui/url/288cdcb32aa667fcbed3911b513e63ea6139b10fdb7994d2f9645bc7f7ba70f1?nocache=1

**Comment by durablenapkin** [comment]
Thank you, queued
