### ISSUE TITLE
Badware

### ISSUE THREAD

**Issue by flav0ring** [durablenapkin/scamblocklist#37]
`youtubebplan.com`

https://www.virustotal.com/gui/url/a4dc20c71685f22f70e7982ae41537ac02276ffb098415128dad100b810973f7?nocache=1

**Comment by iam-py-test** [comment]
> Double.Q Chinese edition telegram

Out of curiosity (please don't take this insultingly), what is malicious about this site?

**Comment by sandrzejewskipl** [comment]
hosting malicious apk
https://twitter.com/malwrhunterteam/status/1651348778065055751
