### ISSUE TITLE
Fake Czech Post and FedEx websites

### ISSUE THREAD

**Issue by tom-b1995** [durablenapkin/scamblocklist#41]
I received 2 SPAM e-mails saying there is a package for me waiting. I have to pay 52.99CZK extra (approximately 2 US Dollars) to get the package(s). They require credit card info and some of the translations in Czech are incorrect. Definitely a scam/phishing website. The FedEx (2nd link) is dead probably.

The links:
https://optimusconstructora.com.pe/blankarokha/herka/ServicesLogin/trika/umzug.php
https://bo-creator-pogu.instawp.xyz/red/

**Comment by durablenapkin** [comment]
Thank you, queued the first - confirmed the second is now suspended :)
