### ISSUE TITLE
Discord scammer

### ISSUE THREAD

**Issue by iam-py-test** [durablenapkin/scamblocklist#67]
An account pretending to be the popular security researcher/YouTuber John Hammond reached out to me on Discord telling me to invest in something.
![325f059f7d06ddfc](https://github.com/durablenapkin/scamblocklist/assets/84232764/d5cdfb83-bba1-4e79-982e-58b583aa0c39)
![c282db50c092db1e](https://github.com/durablenapkin/scamblocklist/assets/84232764/5e4eb856-794a-423a-956f-9ea17f9cc0d5)
More screenshots/info: https://infosec.exchange/@iampytest1/111270258079028453

They gave me these two probably-fake investment websites:
```
metatradebox[.]net
metachartview[.]com
```
I was unable to sign up to either as they block Tor.
Thank you.

**Comment by durablenapkin** [comment]
Thank you very much, both will be added in today's nightly update

**Comment by iam-py-test** [comment]
Thanks
