### ISSUE TITLE
booking scam

### ISSUE THREAD

**Issue by sandrzejewskipl** [durablenapkin/scamblocklist#72]
extracted from virustotal & urlscan

most of them dont have working primary domain A record, so i suggest adding subdomains seperate (i know it's a mess), decision is yours

list is in the text file (too long for an issue)
[booking scam.txt](https://github.com/durablenapkin/scamblocklist/files/13539475/booking.scam.txt)

**Comment by durablenapkin** [comment]
Thanks! I will review

**Comment by durablenapkin** [comment]
Thanks, will be added to next nightly - which does a full check for all domains in raw.txt and only includes the ones with valid A records.
