### ISSUE TITLE
40PlusShag.com (NSFW)

### ISSUE THREAD

**Issue by iam-py-test** [durablenapkin/scamblocklist#76]
This is a fake sex/dating website, which is promoted by:
- bots on Twitter/X DMing links to people
<details>
<summary>Images</summary>
<img width="455" alt="" src="https://github.com/durablenapkin/scamblocklist/assets/84232764/6ab4d051-f506-49b2-9b73-df385c514c8b">
<img width="438" alt="" src="https://github.com/durablenapkin/scamblocklist/assets/84232764/1e4efbf6-49f5-436d-818c-2b0bc9440cc7">
<img width="442" alt="" src="https://github.com/durablenapkin/scamblocklist/assets/84232764/317343c7-bd5c-43a1-91c2-3d430a332c44">
</details>

- those links redirect to `mysuperdatingforyou.life`
- which redirects to `chat-o-live.com`
- which guides users through a sign up process to create an account on 40PlusShag
- during this process, a popup from some subdomain of `fundatingquest.fun` will open. This popup resembles a chat window and requests the user grant the website access to notifications. The window is otherwise nonfunctional and always has the same image.
- users are emailed a confirmation link & redirected to 40PlusShag
- every few minutes, the user will be sent a fake DM from a supposed user of the site
* These DMs are generic, with the user's username and location added in
* These "users" will claim to be located near the user
* The location of these users changes depending on where the user said they live. Two accounts may receive the same DM from the same user, claiming to live in two different places. All other details for the supposed user remain the same (age, profile picture)
* The profile picture and other images are stolen from porn sites
* Replying to these messages requires providing payment information - the site uses a service named Whitelabel Payments

See the following sandbox analysises for more information
**Warning: tria.ge is behind CloudFlare. Proceed with caution**
- https://tria.ge/240224-zxewqafc9v/behavioral1
- https://tria.ge/240224-1ygx5sgc8v/behavioral1
- https://tria.ge/240224-2lmtasgh3v/behavioral1

All related domains:
```
i.fundatingquest.fun
b.fundatingquest.fun
a.fundatingquest.fun
sharlalias.click
mysuperdatingforyou.life
chat-o-live.com
rozaholshouser.cfd
eshaalfawson.shop
```

I can provide more information if needed.
Thank you

**Comment by durablenapkin** [comment]
Thank you for all the info, all domains will be added to the next nightly update.
