### ISSUE TITLE
malicious redirect js

### ISSUE THREAD

**Issue by sandrzejewskipl** [durablenapkin/scamblocklist#77]
```
365analytics.xyz
load.365analytics.xyz
```

**Comment by durablenapkin** [comment]
Thank you, queued to be added in tonight's update :)

**Comment by sandrzejewskipl** [comment]
> Thank you, queued to be added in tonight's update :)

ty
please add also 
`townaptdesk.info`

**Comment by durablenapkin** [comment]
Queued as well, thanks!
