### ISSUE TITLE
*.onlinehome.us

### ISSUE THREAD

**Issue by jarelllama** [durablenapkin/scamblocklist#8]
Common domain for scams. https://github.com/hagezi/dns-blocklists/issues/569

Examples:
https://www.reddit.com/r/Scams/comments/11cwxev/your_amazon_account_has_been_locked_scam_texts_id/
https://www.reddit.com/r/Scams/comments/11vyj6a/ive_been_getting_a_ton_of_text_messages_about/

**Comment by durablenapkin** [comment]
Thanks, queued
