### ISSUE TITLE
Scam Shop: "produktretter"

### ISSUE THREAD

**Issue by StefanZug** [durablenapkin/scamblocklist#80]
Just got a Google Ad from this Scam shop:

- produktretter.at
- produktretter.com (just started a redirect to google.de, but should be blocked, because it could go online anytime again)
- produktretter.org (multiple redirects, but should also be blocked)

Multiple other domains, with the same scam scheme:

- gratis-eltern-produkttests.com
- produkttest-anmeldung.com
- maforia-anmeldung.com
- produkttester-anmeldung.com
- produkttester-werden.org
- produkttest-anmeldung.com
- ruecksendungen-gratis.com

Sources (in German):
1. https://www.watchlist-internet.at/news/vorsicht-vor-abo-falle-auf-produktretterat/
2. https://www.watchlist-internet.at/liste-abo-fallen/abo-falle/produktrettercom/
3. Source: https://www.sir-apfelot.de/produktretter-org-betrug-49480

**Comment by durablenapkin** [comment]
Thank you, queued all of the domains :+1:
