### ISSUE TITLE
Taxes Scam 

### ISSUE THREAD

**Issue by wowfilip999** [durablenapkin/scamblocklist#86]
I seen screenshot on discord with this taxes scam![1283759545562431541remix-1726142565378.png](https://github.com/user-attachments/assets/fd343c5d-c4c8-4e9d-b8c8-16d8011f7055)
![IMG_1761.jpg](https://github.com/user-attachments/assets/4373e396-ee6e-4904-a43a-a34f5b608499)

ww3.dane- cr2024.io.webm.ru

**Comment by durablenapkin** [comment]
Thanks! Queued to be added in tonight's update.
