### ISSUE TITLE
(Add scam site) Fake Poshmark site, this collects CC data

### ISSUE THREAD

**Issue by kerta1n** [durablenapkin/scamblocklist#87]
https://s3-poshmark.id829.com/

![image](https://github.com/user-attachments/assets/2201037c-ba5e-4b00-a144-885f96574bd3)

These scammers are using those CCs to buy CS:GO cases

![image](https://github.com/user-attachments/assets/7cba4d1a-39bf-4a6a-bd49-145b2108facf)

**Comment by durablenapkin** [comment]
Thanks! Will be added in tonight's update
