### ISSUE TITLE
fake facebook meta support 

### ISSUE THREAD

**Issue by wowfilip999** [durablenapkin/scamblocklist#89]
![image](https://github.com/user-attachments/assets/c13220d8-8b7d-424f-944a-89aab017deed)

feji.us (url shortener but it should be in somelist blocked too if it used for scamming)
https://feji.us/facebook-marketsupport

Scam that pretend to be from meta  support they say if you dont verify you account Will be removed

**Comment by durablenapkin** [comment]
Thank you! `facebook-support-team-980.pages.med.br` will be added in tonight's update.

More info: https://github.com/hagezi/dns-blocklists/issues/4153#issuecomment-2452140418
