### ISSUE TITLE
SCAM WEBSITE #KERA99

### ISSUE THREAD

**Issue by Cyneyelash** [durablenapkin/scamblocklist#93]
## Pendahuluan
KERA99 telah dilaporkan sebagai situs scam yang menipu banyak pengguna. Artikel ini akan membahas bagaimana situs ini beroperasi dan cara melindungi diri dari penipuan serupa.

## Cara Kerja
Situs ini menarik pengguna dengan janji hadiah besar atau keuntungan cepat. Setelah pengguna mendaftar dan mungkin melakukan pembayaran, mereka tidak menerima apa yang dijanjikan.

## Tanda-tanda Situs Scam
- **Janji Keuntungan Besar:** Menawarkan keuntungan yang terlalu bagus untuk menjadi kenyataan.
- **Informasi Kontak yang Tidak Jelas:** Tidak ada alamat fisik atau nomor telepon yang dapat dihubungi.
- **Ulasan Negatif:** Banyak ulasan negatif dari pengguna lain di internet.

## Cara Melindungi Diri
- **Verifikasi Informasi:** Selalu periksa keaslian situs sebelum mendaftar.
- **Gunakan Sumber Terpercaya:** Hanya gunakan situs yang sudah dikenal dan terpercaya.
- **Laporkan Penipuan:** Jika Anda menjadi korban, laporkan ke pihak berwenang.

## Issue: 🚀Feature Request
Bagian ini digunakan untuk mengajukan permintaan fitur baru terkait dengan pencegahan atau penanganan situs scam seperti KERA99. Silakan tambahkan detail permintaan fitur Anda di sini.

## Kesimpulan
Selalu berhati-hati dan lakukan penelitian sebelum berinteraksi dengan situs yang tidak dikenal. Keamanan Anda adalah prioritas utama.

**Comment by durablenapkin** [comment]
Dupe of #92
